########################################################
#Title - Diastatic Fracture Manuscript
#Purpose: Compare linear and diastatic fracture morphology
#Last Updated on 12/03/2025 (eh)
#
#Updates:
# 1. 2025/10/13: started the script (eh)
# 2. 2025/10/16: edited statistical analysis
# 3. 2025/10/28: added wilcoxen signed rank tests and formatted data
# 4. 2025/10/30: Added descriptive statistics
# 5. 2025/11/3: Compiled Wilcoxon results into table and exported as csv
# 6. 2025/11/6: Added demographics and tables
# 7. 2025/11/9: Created heatmap of paired differences
# 8. 2025/11/12: Bug Fixes
# 9. 2025/11/17: Table fixes and graph formatting
#10. 2025/11/20: Graph and table formatting
#11. 2025/11/28: Added Table 2 and Figure 1
#12. 2025/12/02: Summary statistics
#13. 2025/12/03: Added median bar graph (Figure 2)

########################################################
#Clean Environment
rm(list=ls())
########################################################
#remove random
set.seed(1234) #Establishes the starting point for calculation
########################################################
#Install/load packages
library(readxl)
library(dplyr)
library(tidyr)
library(ggplot2)
library(stats)
library(gridExtra)
########################################################
#Script 1: Data Organization
########################################################
#Import data and characterize
data<-read_excel("Diastatic_Fracture.xlsx")
str(data) #Analyze structure of data
head(data)
data<-as.data.frame(data) #Store data as a data frame
########################################################
#Organize data
str(data) #Check Structure

#Remove extraneous data
data<-data[c(1:11)]
#Store all variables as ordered, Spec and fx as factors
data<-data %>%
  mutate (
    Spec=as.factor(Spec),
    fx=as.factor(fx),
    hem=as.ordered(hem),
    fib=as.ordered(fib),
    lct=as.ordered(lct),
    fb=as.ordered(fb),
    fct=as.ordered(fct),
    sf=as.ordered(sf),
    nc=as.ordered(nc)
    )
data<-data %>%      
  mutate (
    hem=as.numeric(as.character(hem)),   #Convert ordered factors to numerical values
    fib=as.numeric(as.character(fib)),
    lct=as.numeric(as.character(lct)),
    fb=as.numeric(as.character(fb)),
    fct=as.numeric(as.character(fct)),
    sf=as.numeric(as.character(sf)),
    nc=as.numeric(as.character(nc))
  )

#Create new columns for age and injury categories
df<-data%>%
  mutate(
    age=case_when(
      decage>16~"Adult",
      decage>3 & decage<=16~"Juvenile",
      TRUE~NA_character_),
    injury_age=case_when(
      inage>7~"8-30 days",
      inage>=1 & inage<=7~"1-7 days",
    )
  )


########################################################
#Script 2: #Demographic Summary and Descriptive Stats
########################################################

#Create sample demographics table
tab1<-addmargins(xtabs(~age+injury_age+fx, data=df))
tab1.1<-ftable(tab1)
write.ftable(tab1.1, "Table 1.csv", quote=FALSE)

#Filter data to fracture group and variables
df1<-df[c(2,5:11)]
#Rename variables to full name
names(df1)[2:8]<-c("Hematoma", "Fibrin", "Loose CT", "Fibroblasts", "Fibrous CT", "Sharpey's Fibers", "New Capillaries")

#Create distribution table of scores for fracture groups - assisted by Chat GPT (GPT 5.1), Open AI. Accessed 2025-11-28.
vars<-c("Hematoma", "Fibrin", "Loose CT", "Fibroblasts", "Fibrous CT", "Sharpey's Fibers", "New Capillaries")
disttab.F<-df1%>%       #Linear fracture scores
  filter(fx=="LF") %>%
  pivot_longer(cols=vars,
               names_to="Variable",
               values_to="score") %>%
  count(Variable, score) %>%
  pivot_wider(names_from=score,
              values_from=n,
              values_fill=0)

disttab.DF<-df1%>%       #Diastatic fracture scores
  filter(fx=="DF") %>%
  pivot_longer(cols=vars,
               names_to="Variable",
               values_to="score") %>%
  count(Variable, score) %>%
  pivot_wider(names_from=score,
              values_from=n,
              values_fill=0)
#Export as Table 2
write.table(disttab.F, "Table 2.csv", col.names=TRUE, sep=",")
write.table(disttab.DF, "Table 2.csv", col.names=FALSE, sep="," ,append=TRUE)


#Create a table of summary statistics

#Fracture data summary statistics
LF.table<-df1%>%         #create new data frame for F data
  filter(fx=="LF")

sum_stats_LF<-LF.table%>% #calculate summary statistics
  select(vars)%>%
  summarize_all(list(Median=median, Min=min, Max=max, IQR=IQR))

stats_LF<-sum_stats_LF%>%   #create aesthetic table of summary statistics
  pivot_longer(everything(),
               names_to=c("Feature", "Statistic"),
               names_pattern = "([^_]+)_(.+)")%>%   #code generated by HuggingFace AI Assistant, 2025/12/02
  pivot_wider(names_from=Statistic,
              values_from=value)


#Diastatic data summary statistics

DF.table<-df1%>%        #create new data frame for DF data
  filter(fx=="DF")

sum_stats_DF<-DF.table%>%  #calculate summary statistics
  select(vars)%>%
  summarize_all(list(Median=median, Min=min, Max=max, IQR=IQR))

stats_DF<-sum_stats_DF%>%   #create aesthetic table
  pivot_longer(everything(),
               names_to=c("Feature", "Statistic"),
               names_pattern = "([^_]+)_(.+)")%>%   #code generated by HuggingFace AI Assistant, 2025/12/02
  pivot_wider(names_from=Statistic,
              values_from=value)
#Export as Table 3
write.table(stats_LF, "Table 3.csv", col.names=TRUE, sep=",")
write.table(stats_DF, "Table 3.csv", col.names=TRUE, sep=",", append=TRUE)




#Create distribution plots - Figure 1

a<-ggplot(data, aes(x=fib, fill=fx)) + geom_bar(color="black", position="dodge") + theme_bw()+labs(x="Fibrin")+
  scale_fill_manual(values=c("white", "black"))
b<-ggplot(data, aes(x=fb, fill=fx)) + geom_bar(color="black", position="dodge") + theme_bw()+labs(x="Fibroblasts")+
  scale_fill_manual(values=c("white", "black"))
c<-ggplot(data, aes(x=fct, fill=fx)) + geom_bar(color="black", position="dodge") + theme_bw()+labs(x="Fibrous CT")+
  scale_fill_manual(values=c("white", "black"))
d<-ggplot(data, aes(x=hem, fill=fx)) + geom_bar(color="black", position="dodge") + theme_bw()+labs(x="Hematoma")+
  scale_fill_manual(values=c("white", "black"))
f<-ggplot(data, aes(x=lct, fill=fx)) + geom_bar(color="black", position="dodge") + theme_bw()+labs(x="Loose CT")+
  scale_fill_manual(values=c("white", "black"))
g<-ggplot(data, aes(x=nc, fill=fx)) + geom_bar(color="black", position="dodge") + theme_bw()+labs(x="New Capillaries")+
  scale_fill_manual(values=c("white", "black"))
h<-ggplot(data, aes(x=sf, fill=fx)) + geom_bar(color="black", position="dodge") + theme_bw()+labs(x="Sharpey's Fibers")+
  scale_fill_manual(values=c("white", "black"))


grid.arrange(a,b,c,d,f,g,h,nrow=4)

#Create Figure 2: Median Expression Trends

#Calculate medians
my.medians<-data%>%
  group_by(fx)%>%
  summarize(Hematoma=median(hem), Fibrin=median(fib), Loose_CT=median(lct),
            Fibroblasts=median(fb), Fibrous_CT=median(fct), Sharpeys_Fibers=median(sf),
            Capillaries=median(nc))

#Rename variables
names(my.medians)[4]<-c("Loose CT")
names(my.medians)[6:8]<-c("Fibrous CT", "Sharpey's Fibers", "New Capillaries") 

#Melt data set
melt_medians <- my.medians %>%
  pivot_longer(
    cols = -fx,                    
    names_to = "Features",       
    values_to = "Value"              
  )

#Create medians bar chart
fig2<-ggplot(melt_medians, aes(Features, Value, fill=fx))+
  geom_col(color="black", position="dodge")+
  theme_classic()+
  scale_fill_manual(values=c("#d73027", "#4575b4"))+
  labs(x="Features", y="Median Expression")+
  theme(axis.text.x=element_text(angle=45, vjust=1, hjust=1))
fig2

########################################################
#Script 3: Statistical Analysis
########################################################
#Create wide format
features<-c("hem", "fib", "lct", "fb", "fct", "sf", "nc")
data_wide<-pivot_wider(
  df,
  names_from = fx, 
  values_from = features
)

#Run Wilcox Signed Rank Tests for all variables
hem_wil<-wilcox.test(data_wide$hem_LF, data_wide$hem_DF, paired=TRUE, exact=FALSE)
fib_wil<-wilcox.test(data_wide$fib_LF, data_wide$fib_DF, paired=TRUE, exact=FALSE)
lct_wil<-wilcox.test(data_wide$lct_LF, data_wide$lct_DF, paired=TRUE, exact=FALSE)
fb_wil<-wilcox.test(data_wide$fb_LF, data_wide$fb_DF, paired=TRUE, exact=FALSE)
fct_wil<-wilcox.test(data_wide$fct_LF, data_wide$fct_DF, paired=TRUE, exact=FALSE)
sf_wil<-wilcox.test(data_wide$sf_LF, data_wide$sf_DF, paired=TRUE, exact=FALSE)
nc_wil<-wilcox.test(data_wide$nc_LF, data_wide$nc_DF, paired=TRUE, exact=FALSE)


#Create list of Wilcoxon results
wil_results<-list(hem_wil, fib_wil, lct_wil, fb_wil, 
                  fct_wil, sf_wil, nc_wil)

#Designate variable names
names(wil_results)<-c("Hematoma", "Fibrin", "Loose C.T.",
                          "Fibroblasts", "Fibrous C.T.", "Sharpey's Fibers", "New Capillaries")
#Create V value and p-value objects
V_value<-sapply(wil_results, function(x) x$statistic)
p_value<-sapply(wil_results, function(x) x$p.value)

#Combine V and p-values into tablemean<-sapply(sum_stats, function(x) x$mean)
stats_table<-data.frame(
  Variable=names(wil_results),
  V=V_value,
  p.value=p_value,
  row.names=NULL
)

write.csv(stats_table, "Table 5.csv") #Save as csv


#Paired Differences and Heatmap
pair_diff<- data_wide%>%            #Calculate paired differences
  mutate(
    Hematoma = hem_LF-hem_DF,
    Fibrin = fib_LF-fib_DF,
    Loose_C.T. = lct_LF-lct_DF,
    Fibroblasts = fb_LF-fb_DF,
    Fibrous_C.T. = fct_LF-fct_DF,
    Sharpeys_Fibers = sf_LF-sf_DF,
    New_Capillaries = nc_LF-nc_DF
  )
pair_diff2<-pair_diff[c(1, 20:26)]
names(pair_diff2)[4]<-c("Loose CT")
names(pair_diff2)[6:8]<-c("Fibrous CT", "Sharpey's Fibers", "New Capillaries")
#Save paired difference calculations as a table
write.csv(pair_diff2, "Paired Differences.csv")

#Transform data to long format  
melt_data <- pair_diff2 %>%
  pivot_longer(
    cols = -Spec,                    
    names_to = "Features",       
    values_to = "Value"              
  )

#Create heatmap
fig3<-ggplot(melt_data, aes(x=Features, y=Spec, fill=Value)) +
  geom_tile(color="black")+          #Create heatmap with black borders
  scale_fill_gradient2(              #Designate colors for scale
    low="#d73027",
    mid="white",
    high="#4575b4",
    midpoint=0) +
  theme_minimal()+
  scale_x_discrete(position="top") +  #Move x labels to top
  theme(axis.text.x.top = element_text(
    angle=25,                         #Angle x labels
    vjust=0.5,                        #Adjust height 
    hjust=0.5,                       #Center labels
    size=10)) +                     #Adjust size
  scale_y_discrete(limits=rev)+       #Reverse y-axis order
  labs(x="", y="Individual", 
       title="Paired Differences Between Fracture Features")+
  theme(plot.title=element_text(hjust=0.5)) #Center title
fig3

########################################################

